# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custormer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='名称', help_text='客户名称', max_length=20)),
                ('email', models.CharField(blank=True, default='', help_text='邮箱', max_length=30, null=True)),
                ('company', models.CharField(default='', help_text='公司名称', max_length=40, null=True)),
                ('address', models.CharField(default='', help_text='地址', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', help_text='手机号', max_length=16, null=True)),
                ('mobile', models.CharField(blank=True, default='', help_text='固定电话', max_length=20, null=True)),
                ('qq', models.CharField(blank=True, default='', help_text='qq', max_length=20, null=True)),
                ('wechat', models.CharField(blank=True, default='', help_text='微信号', max_length=20, null=True)),
                ('web', models.CharField(blank=True, default='', help_text='网站', max_length=50, null=True)),
                ('industry', models.CharField(blank=True, default='', help_text='行业', max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='公司简介', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', help_text='标题', max_length=64)),
                ('create_date', models.DateTimeField(help_text='创建时间')),
                ('deadline', models.DateTimeField(help_text='截止时间')),
                ('state', models.IntegerField(default=0, help_text='状态,0-->草稿,1-->待审核,2-->审核失败,3-->审核成功,4-->发布成功')),
                ('quantity', models.IntegerField(default=1, help_text='发布数量')),
                ('free_count', models.IntegerField(default=1, help_text='可用问卷数量')),
                ('cusomer', models.ForeignKey(help_text='客户信息', on_delete=django.db.models.deletion.CASCADE, to='myapp.Custormer')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='姓名', help_text='姓名', max_length=15, null=True)),
                ('age', models.IntegerField(default=1, help_text='年龄')),
                ('gender', models.BooleanField(default='male', help_text='性别', max_length=18)),
                ('phone', models.CharField(blank=True, default='', help_text='手机号码', max_length=16, null=True)),
                ('email', models.EmailField(blank=True, default='', help_text='邮箱', max_length=254, null=True)),
                ('address', models.CharField(blank=True, default='', help_text='地址', max_length=256, null=True)),
                ('birthday', models.DateField(default=datetime.date(2018, 1, 1), help_text='出生日期', null=True)),
                ('qq', models.CharField(blank=True, default='', help_text='qq', max_length=16, null=True)),
                ('wechat', models.CharField(blank=True, default='', help_text='微信', max_length=16, null=True)),
                ('job', models.CharField(blank=True, default='', help_text='工作', max_length=64, null=True)),
                ('salary', models.CharField(blank=True, default='', help_text='薪水', max_length=32, null=True)),
            ],
        ),
    ]
